SET NAMES utf8mb4;
SET character_set_client = utf8mb4;
SET character_set_connection = utf8mb4;
SET character_set_results = utf8mb4;

-- 1. 데이터베이스 생성 및 선택
CREATE DATABASE IF NOT EXISTS matgotdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE matgotdb;

-- -- 2. 관리자 계정 생성 및 권한 부여
-- CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY '2222';
-- CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY '2222';
-- GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%';
-- GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost';
-- FLUSH PRIVILEGES;

-- 3. 회원 테이블 생성
CREATE TABLE `MEMBER_TBL` (
`member_no`              BIGINT   NOT NULL AUTO_INCREMENT,
`member_id`       VARCHAR(50)       NOT NULL,
`member_pw`       CHAR(60)          NOT NULL,
`member_name`     VARCHAR(30)       NOT NULL,
`member_email`    VARCHAR(50)       NOT NULL,
`member_nickname` VARCHAR(20)       NOT NULL,
`member_thumb`    VARCHAR(255)      NULL,
`member_address`  VARCHAR(300)  NULL,
`member_status`   TINYINT UNSIGNED  NOT NULL DEFAULT 0 COMMENT '0:정상/1:비정상',
`enroll_date`     DATETIME          NOT NULL DEFAULT CURRENT_TIMESTAMP,
`admin`           BOOLEAN           NOT NULL DEFAULT 0 COMMENT '0:일반회원/1:관리자',
`lat`                                DOUBLE,
`lng`                                DOUBLE,
`ad_content`        TINYINT UNSIGNED        NULL        DEFAULT 0        COMMENT '0:수신비동의/1:메일수신동의/2.문자수신동의/3:이메일문자수신종의',
PRIMARY KEY (`member_no`),
UNIQUE KEY `UQ_MEMBER_ID`       (`member_id`),
UNIQUE KEY `UQ_MEMBER_EMAIL`    (`member_email`),
UNIQUE KEY `UQ_MEMBER_NICKNAME` (`member_nickname`)
);

-- 🔥 [중요] 외래키 에러 방지를 위해 테스트 멤버(test01) 데이터 먼저 삽입!
INSERT INTO `MEMBER_TBL` (`member_id`, `member_pw`, `member_name`, `member_email`, `member_nickname`)
VALUES ('test01', '$2a$10$xyz...', '테스터', 'test01@matgot.com', '맛갓나그네');

-- 4. 기타 회원 관련 테이블 생성
CREATE TABLE `NATIVES_TBL` (
`native_no`       BIGINT       NOT NULL AUTO_INCREMENT,
`member_id`       VARCHAR(20)  NULL,
`region`          VARCHAR(50)  NOT NULL COMMENT '시도 시군구 동면읍',
`native_deadline` DATETIME     NULL COMMENT 'NULL이면 제한 없음',
PRIMARY KEY (`native_no`),
INDEX `idx_member_id` (`member_id`),
CONSTRAINT `fk_natives_member`
FOREIGN KEY (`member_id`)
   REFERENCES `MEMBER_TBL` (`member_id`)
   ON DELETE SET NULL
   ON UPDATE CASCADE
);

CREATE TABLE `LOGIN_LOG_TBL` (
`login_no`      BIGINT           NOT NULL AUTO_INCREMENT,
`member_no`     BIGINT           NULL,
`login_status`  TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0:로그아웃/1:로그인',
`login_time`    DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`login_no`),
INDEX `idx_member_no` (`member_no`),
CONSTRAINT `fk_login_member`
 FOREIGN KEY (`member_no`)
     REFERENCES `MEMBER_TBL` (`member_no`)
     ON DELETE SET NULL
     ON UPDATE CASCADE
);

CREATE TABLE `SOCIAL_LOGIN_TBL` (
`social_no`     BIGINT    NOT NULL AUTO_INCREMENT,
`member_no`     BIGINT    NULL,
`social_google` DATETIME  NULL,
`social_kakao`  DATETIME  NULL,
`social_naver`  DATETIME  NULL,
`social_apple`  DATETIME  NULL,
PRIMARY KEY (`social_no`),
INDEX `idx_member_no` (`member_no`),
CONSTRAINT `fk_social_member`
    FOREIGN KEY (`member_no`)
        REFERENCES `MEMBER_TBL` (`member_no`)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- 5. 맛집 관련 테이블 생성
CREATE TABLE restaurant_tbl (
rest_no BIGINT AUTO_INCREMENT PRIMARY KEY,
member_id VARCHAR(50) NOT NULL,
rest_name VARCHAR(100) NOT NULL,
rest_addr VARCHAR(255) NOT NULL,
lat DOUBLE NOT NULL,
lng DOUBLE NOT NULL,
category VARCHAR(50) NOT NULL,
phone VARCHAR(20),
hours VARCHAR(100),
rating_sum INT NOT NULL DEFAULT 0,
review_total_count INT NOT NULL DEFAULT 0,
local_review_count INT NOT NULL DEFAULT 0,
rest_content TEXT NOT NULL,
ai_review TEXT,
rest_status VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
rest_thumb varchar(300),
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uk_same_restaurant UNIQUE (rest_name, rest_addr),
CONSTRAINT fk_restaurant_writer FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE
);

CREATE TABLE rest_report_tbl (
rest_rp_no BIGINT AUTO_INCREMENT PRIMARY KEY,
member_id VARCHAR(50) NOT NULL,
rest_no BIGINT NOT NULL,
reason VARCHAR(50) NOT NULL CHECK (reason IN ('허위정보', '욕설비방', '광고스팸', '기타')),
detail TEXT,
report_status TINYINT NOT NULL DEFAULT 0 CHECK (report_status IN (0, 1, 2)),
report_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_rest_report_member FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE,
CONSTRAINT fk_report_restaurant FOREIGN KEY (restaurant_tbl) REFERENCES restaurant_tbl(rest_no) ON DELETE CASCADE,
CONSTRAINT uk_report_unique_rest UNIQUE (member_id, rest_no)
);

CREATE TABLE rest_like_tbl (
member_id VARCHAR(50) NOT NULL,
rest_no BIGINT NOT NULL,
CONSTRAINT pk_like_rest PRIMARY KEY (member_id, rest_no),
CONSTRAINT fk_like_member FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE,
CONSTRAINT fk_like_restaurant FOREIGN KEY (rest_no) REFERENCES restaurant_tbl(rest_no) ON DELETE CASCADE
);

CREATE TABLE review_tbl (
review_no BIGINT AUTO_INCREMENT PRIMARY KEY,
member_id VARCHAR(50) NOT NULL,
rest_no BIGINT NOT NULL,
review_content TEXT NOT NULL,
rating TINYINT UNSIGNED NOT NULL CHECK (rating BETWEEN 1 AND 5),
visit_date DATE NOT NULL,
is_local_review BOOLEAN NOT NULL DEFAULT FALSE,
review_status TINYINT NOT NULL DEFAULT 0,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_review_member FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE,
CONSTRAINT fk_review_restaurant FOREIGN KEY (rest_no) REFERENCES restaurant_tbl(rest_no) ON DELETE CASCADE
);

CREATE TABLE review_menu_tbl (
review_menu_no BIGINT AUTO_INCREMENT PRIMARY KEY,
review_no BIGINT NOT NULL,
menu_name VARCHAR(100) NOT NULL,
CONSTRAINT uk_review_menu UNIQUE (review_no, menu_name),
CONSTRAINT fk_review_menu_review FOREIGN KEY (review_no) REFERENCES review_tbl(review_no) ON DELETE CASCADE
);

CREATE TABLE review_tags_tbl(
review_tags_no BIGINT AUTO_INCREMENT PRIMARY KEY,
review_no BIGINT NOT NULL,
tag_name VARCHAR(30) NOT NULL,
CONSTRAINT uq_review_tag UNIQUE (review_no, tag_name),
CONSTRAINT fk_review_tags_tbl_review FOREIGN KEY (review_no) REFERENCES review_tbl(review_no) ON DELETE CASCADE
);

CREATE TABLE review_images_tbl (
review_image_no BIGINT AUTO_INCREMENT PRIMARY KEY,
review_no BIGINT NOT NULL,
image_url VARCHAR(500) NOT NULL,
CONSTRAINT fk_review_image FOREIGN KEY (review_no) REFERENCES review_tbl(review_no) ON DELETE CASCADE
);

CREATE TABLE review_like_tbl(
review_no BIGINT NOT NULL,
member_id VARCHAR(50) NOT NULL,
CONSTRAINT pk_like_review PRIMARY KEY (review_no, member_id),
CONSTRAINT fk_review_like_member FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE,
CONSTRAINT fk_review_like_review FOREIGN KEY (review_no) REFERENCES review_tbl(review_no) ON DELETE CASCADE
);

CREATE TABLE review_report_tbl (
review_rp_no BIGINT AUTO_INCREMENT PRIMARY KEY,
member_id VARCHAR(50) NOT NULL,
review_no BIGINT NOT NULL,
reason VARCHAR(50) NOT NULL CHECK (reason IN ('허위정보', '욕설비방', '광고스팸', '기타')),
detail TEXT,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
report_status TINYINT NOT NULL DEFAULT 0 CHECK (report_status IN (0, 1, 2)),
CONSTRAINT fk_review_report_review FOREIGN KEY (review_no) REFERENCES review_tbl(review_no) ON DELETE CASCADE,
CONSTRAINT fk_review_report_member FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE,
CONSTRAINT uk_review_report UNIQUE (member_id, review_no)
);

CREATE TABLE review_comment_tbl (
comment_no BIGINT AUTO_INCREMENT PRIMARY KEY,
review_no BIGINT NOT NULL,
member_id VARCHAR(50) NOT NULL,
parent_comment BIGINT,
depth TINYINT UNSIGNED NOT NULL DEFAULT 0 CHECK (depth IN (0,1)),
content TEXT NOT NULL,
com_status TINYINT UNSIGNED NOT NULL DEFAULT 0,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_review_comment_review FOREIGN KEY (review_no) REFERENCES review_tbl(review_no) ON DELETE CASCADE,
CONSTRAINT fk_review_comment_member FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE,
CONSTRAINT fk_review_comment_parent FOREIGN KEY (parent_comment) REFERENCES review_comment_tbl(comment_no) ON DELETE CASCADE
);

CREATE TABLE review_comment_report_tbl (
review_com_rp_no BIGINT AUTO_INCREMENT PRIMARY KEY,
member_id VARCHAR(50) NOT NULL,
comment_no BIGINT NOT NULL,
reason VARCHAR(50) NOT NULL CHECK (reason IN ('허위정보', '욕설비방', '광고스팸', '기타')),
detail TEXT,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
report_status TINYINT NOT NULL DEFAULT 0 CHECK (report_status IN (0, 1, 2)),
       CONSTRAINT fk_report_com_member FOREIGN KEY (member_id) REFERENCES MEMBER_TBL(member_id) ON DELETE CASCADE,
       CONSTRAINT fk_report_com_comment FOREIGN KEY (comment_no) REFERENCES review_comment_tbl(comment_no) ON DELETE CASCADE,
       CONSTRAINT uk_report_unique_comment UNIQUE (member_id, comment_no)
);

-- 6. 커뮤니티 게시판 관련 테이블 생성
CREATE TABLE BOARD_PLACE_TBL (
PLACE_NO BIGINT NOT NULL AUTO_INCREMENT,
PLACE_NAME VARCHAR(150) NOT NULL,
ADDRESS_NAME VARCHAR(260) NOT NULL,
PLACE_LAT DOUBLE NULL,
PLACE_LNG DOUBLE NULL,
PRIMARY KEY (PLACE_NO),
UNIQUE KEY UQ_PLACE (PLACE_NAME, ADDRESS_NAME)
);

CREATE TABLE BOARD_TBL (
BOARD_NO BIGINT NOT NULL AUTO_INCREMENT,
MEMBER_NO BIGINT NOT NULL,
BOARD_CATEGORY INT NOT NULL COMMENT '1:여행후기 / 2:자유게시글',
BOARD_TITLE VARCHAR(150) NOT NULL,
BOARD_CONTENT MEDIUMTEXT NOT NULL,
BOARD_THUMB VARCHAR(500) NULL,
BOARD_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
BOARD_STATUS TINYINT NOT NULL DEFAULT 1 COMMENT '0:관리자비공개 / 1:공개 / 2:삭제',
PLACE_NO BIGINT NOT NULL,
BOARD_VIEW BIGINT NOT NULL DEFAULT 0,
PRIMARY KEY (BOARD_NO),
CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER_TBL(MEMBER_NO) ON DELETE CASCADE,
CONSTRAINT FK_BOARD_PLACE FOREIGN KEY (PLACE_NO) REFERENCES BOARD_PLACE_TBL(PLACE_NO) ON DELETE CASCADE
);

CREATE TABLE BOARD_LIKE_TBL (
MEMBER_NO BIGINT NOT NULL,
BOARD_NO  BIGINT NOT NULL,
PRIMARY KEY (MEMBER_NO, BOARD_NO),
CONSTRAINT FK_BOARD_LIKE_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER_TBL(MEMBER_NO) ON DELETE CASCADE,
CONSTRAINT FK_BOARD_LIKE_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD_TBL(BOARD_NO) ON DELETE CASCADE
);

CREATE TABLE BOARD_COMMENT_TBL (
BOARD_COMMENT_NO BIGINT NOT NULL AUTO_INCREMENT,
BOARD_COMMENT_CONTENT VARCHAR(4000) NOT NULL,
BOARD_COMMENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MEMBER_NO BIGINT NOT NULL,
BOARD_COMMENT_STATUS TINYINT NOT NULL DEFAULT 1 COMMENT '0:관리자비공개 / 1:공개 / 2:삭제',
BOARD_NO BIGINT NOT NULL,
PRIMARY KEY (BOARD_COMMENT_NO),
CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER_TBL(MEMBER_NO) ON DELETE CASCADE,
CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD_TBL(BOARD_NO) ON DELETE CASCADE
);

CREATE TABLE BOARD_REPORT_TBL (
BOARD_REPORT_NO BIGINT NOT NULL AUTO_INCREMENT,
MEMBER_NO BIGINT NOT NULL,
BOARD_NO BIGINT NOT NULL,
REPORT_REASON VARCHAR(100) NOT NULL COMMENT '허위정보, 욕설비방, 광고스팸, 기타',
REPORT_STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '0:처리대기, 1:처리완료, 2:반려',
DETAIL TEXT NULL,
REPORT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (BOARD_REPORT_NO),
CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER_TBL(MEMBER_NO) ON DELETE CASCADE,
CONSTRAINT FK_REPORT_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD_TBL(BOARD_NO) ON DELETE CASCADE
);

CREATE TABLE BOARD_COMMENT_REPORT_TBL (
      COMMENT_REPORT_NO BIGINT NOT NULL AUTO_INCREMENT,
      MEMBER_NO BIGINT NOT NULL,
      BOARD_COMMENT_NO BIGINT NOT NULL,
      REPORT_REASON VARCHAR(100) NOT NULL COMMENT '허위정보, 욕설비방, 광고스팸, 기타',
      REPORT_STATUS TINYINT NOT NULL DEFAULT 0 COMMENT '0:처리대기, 1:처리완료, 2:반려',
      DETAIL TEXT NULL,
      REPORT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (COMMENT_REPORT_NO),
      CONSTRAINT FK_COMMENT_REPORT_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER_TBL(MEMBER_NO) ON DELETE CASCADE,
      CONSTRAINT FK_COMMENT_REPORT_COMMENT FOREIGN KEY (BOARD_COMMENT_NO) REFERENCES BOARD_COMMENT_TBL(BOARD_COMMENT_NO) ON DELETE CASCADE
);

-- 7. 여행 계획 및 태그 테이블 생성
CREATE TABLE TAG_TBL (
tag_no INT PRIMARY KEY AUTO_INCREMENT,
tag_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MENU_TBL (
MENU_NO BIGINT NOT NULL AUTO_INCREMENT,
REST_NO BIGINT NOT NULL,
MENU_NAME VARCHAR(1000) NOT NULL,
MENU_PRICE INT NOT NULL,
MENU_IMG VARCHAR(3000) NOT NULL,
PRIMARY KEY (MENU_NO),
CONSTRAINT FK_MENU_RESTAURANT FOREIGN KEY (REST_NO) REFERENCES restaurant_tbl (REST_NO) ON DELETE CASCADE
);

CREATE TABLE TRAVEL_PLAN_TBL (
tplan_no BIGINT NOT NULL AUTO_INCREMENT COMMENT '여행계획번호',
member_no BIGINT NOT NULL COMMENT '작성자',
tplan_title VARCHAR(230) NOT NULL COMMENT '제목',
tplan_desc VARCHAR(1000) NULL COMMENT '설명',
tplan_region VARCHAR(100) NULL COMMENT '지역',
tplan_days INT NOT NULL DEFAULT 1 COMMENT '여행일수',
tplan_status TINYINT NOT NULL DEFAULT 1 COMMENT '0:비공개 1:공개',
tplan_total_price INT NOT NULL DEFAULT 0 COMMENT '총 예상비용',
tplan_view INT NOT NULL DEFAULT 0 COMMENT '조회수',
tplan_like INT NOT NULL DEFAULT 0 COMMENT '좋아요수',
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (tplan_no),
CONSTRAINT FK_TRAVEL_PLAN_MEMBER FOREIGN KEY (member_no) REFERENCES MEMBER_TBL (member_no) ON DELETE CASCADE
);

CREATE TABLE PLAN_TAG_TBL (
tplan_no BIGINT NOT NULL,
tag_no INT NOT NULL,
PRIMARY KEY (tplan_no, tag_no),
CONSTRAINT FK_PLAN_TAG_PLAN FOREIGN KEY (tplan_no) REFERENCES TRAVEL_PLAN_TBL (tplan_no) ON DELETE CASCADE,
CONSTRAINT FK_PLAN_TAG_TAG FOREIGN KEY (tag_no) REFERENCES TAG_TBL (tag_no) ON DELETE CASCADE
);

CREATE TABLE TRAVEL_SCHEDULE_TBL (
 tsche_no BIGINT NOT NULL AUTO_INCREMENT COMMENT '여행일정번호',
 tplan_no BIGINT NOT NULL COMMENT '여행계획번호',
 tsche_day_no INT NOT NULL COMMENT '몇일차',
 tsche_order_no INT NOT NULL COMMENT '순서',
 rest_no BIGINT NOT NULL COMMENT '맛집번호',
 PRIMARY KEY (tsche_no),
 CONSTRAINT FK_SCHEDULE_PLAN FOREIGN KEY (tplan_no) REFERENCES TRAVEL_PLAN_TBL (tplan_no) ON DELETE CASCADE,
 CONSTRAINT FK_SCHEDULE_RESTAURANT FOREIGN KEY (rest_no) REFERENCES restaurant_tbl (rest_no) ON DELETE CASCADE
);

CREATE TABLE RECOMMEND_MENU_TBL (
tsche_no BIGINT NOT NULL,
menu_no BIGINT NOT NULL,
PRIMARY KEY (tsche_no, menu_no),
CONSTRAINT FK_RECOMMEND_MENU_SCHEDULE FOREIGN KEY (tsche_no) REFERENCES TRAVEL_SCHEDULE_TBL (tsche_no) ON DELETE CASCADE,
CONSTRAINT FK_RECOMMEND_MENU_MENU FOREIGN KEY (menu_no) REFERENCES MENU_TBL (MENU_NO) ON DELETE CASCADE
);

CREATE TABLE TRAVEL_ROUTE_TBL (
troute_no BIGINT NOT NULL AUTO_INCREMENT COMMENT '이동정보번호',
from_tsche_no BIGINT NOT NULL COMMENT '출발 일정번호',
to_tsche_no BIGINT NOT NULL COMMENT '도착 일정번호',
transit_type VARCHAR(10) NOT NULL COMMENT 'WALK, PUB, CAR',
PRIMARY KEY (troute_no),
CONSTRAINT FK_ROUTE_FROM FOREIGN KEY (from_tsche_no) REFERENCES TRAVEL_SCHEDULE_TBL (tsche_no) ON DELETE CASCADE,
CONSTRAINT FK_ROUTE_TO FOREIGN KEY (to_tsche_no) REFERENCES TRAVEL_SCHEDULE_TBL (tsche_no) ON DELETE CASCADE,
CONSTRAINT CHK_TRANSIT_TYPE CHECK (transit_type IN ('WALK', 'PUB', 'CAR'))
);

CREATE TABLE FAVORITE_PLAN_TBL (
member_no BIGINT NOT NULL COMMENT '회원번호',
tplan_no BIGINT NOT NULL COMMENT '여행계획번호',
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '찜한일시',
PRIMARY KEY (member_no, tplan_no),
CONSTRAINT FK_FAVORITE_MEMBER FOREIGN KEY (member_no) REFERENCES MEMBER_TBL (member_no) ON DELETE CASCADE,
CONSTRAINT FK_FAVORITE_PLAN FOREIGN KEY (tplan_no) REFERENCES TRAVEL_PLAN_TBL (tplan_no) ON DELETE CASCADE
);

INSERT INTO TAG_TBL (tag_name) VALUES
('감성'), ('분위기좋은'), ('조용한'), ('힙한'), ('뷰맛집'),
('사진맛집'), ('연인과'), ('가족과'), ('친구와'), ('혼밥'),
('단체모임'), ('가성비'), ('푸짐한'), ('디저트맛집'), ('커피맛집'),
('숨은맛집'), ('현지인추천'), ('데이트'), ('드라이브'), ('먹방코스');
